---
public: false
name: wtf
description: 
imagePath: 
author: 
organization: 
organizationUrl: 
version: 0.1.0
updateDate: 5/1/2016
defaultPlaybook: playbook.yml
tags:
  - OSS

fields:
- name: dc
  displayName: Datacenter
  type: datacenters  
  required: true
- name: server_id
  displayName: Servers
  parent: dc
  required: true
  type: servers
  detail: false


